### ISSUE TITLE
heroku docs is down

### ISSUE THREAD

**Issue by omgbox** [Davenchy/live-torrent-backend#71]
hi, where can i find api information , the heroku site is offline.

**Comment by Davenchy** [comment]
you can clone and build it locally

**Comment by Davenchy** [comment]
Hello, @omgbox 
My Heroku account was suspended, likely because LiveTorrent is a P2P application that uses the BitTorrent protocol. I don't recommend hosting your own clone on Heroku. Be sure to read the rules of any hosting service before hosting LiveTorrent.

Regarding the API information, I have rewritten the entire server and updated the documentation. The new documentation uses OpenAPI/Swagger. Please check the README for more information, and feel free to ask any questions at any time.
